name: 'Seal bootc image'
description: 'Seals a bootc image'
inputs:
  input-image:
    description: 'Input image to seal'
    required: true
    default: 'World'
  output-image:
    description: 'Name of the generated sealed image'
    required: true
  signing-key:
    required: true
  signing-cert:
    required: true
  cmdline:
    required: true
  sudo:
    required: false
    default: 'sudo'
runs:
  using: "composite"
  steps:
    - name: Setup environment
      uses: bootc-dev/actions/bootc-ubuntu-setup@main
    - name: "Get Secure Boot signing key"
      run: |
        mkdir -p /tmp/keys
        printenv SB_KEY > /tmp/keys/key
        printenv SB_CRT > /tmp/keys/crt
      env:
        SB_KEY: "${{ inputs.signing-key }}"
        SB_CRT: "${{ inputs.signing-cert }}"
      shell: bash
    - name: Build sealed image
      run: $SUDO podman build -t "$OUTPUT_IMAGE" --no-cache --skip-unused-stages=false -v $(pwd):/run/src --build-arg IMAGE="$INPUT_IMAGE" --build-arg CMDLINE="$CMDLINE" --secret=id=secureboot_key,src=/tmp/keys/key --secret=id=secureboot_cert,src=/tmp/keys/crt -f "${{ github.action_path }}/Containerfile.uki" .
      shell: bash
      env:
        INPUT_IMAGE: "${{ inputs.input-image }}"
        OUTPUT_IMAGE: "${{ inputs.output-image }}"
        CMDLINE: "${{ inputs.cmdline }}"
        SUDO: "${{ inputs.sudo }}"
    - name: "Cleanup Secure Boot signing key"
      if: always()
      run: rm -vrf /tmp/keys
      shell: bash

