ARG IMAGE
ARG CMDLINE
FROM $IMAGE as base

FROM registry.fedoraproject.org/fedora-minimal:44 as signer
RUN --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/tmp \
    --mount=type=tmpfs,target=/var \
    <<EORUN
set -euxo pipefail
dnf install -y systemd-ukify sbsigntools jq
dnf install -y --enablerepo=updates-testing --refresh bootc
EORUN

FROM base as base-sd-signed
RUN --network=none \
    --mount=type=secret,id=secureboot_key \
    --mount=type=secret,id=secureboot_cert \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/var/tmp \
sh -euxo pipefail -c '\
    dracut --force "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E ".img" | tail -n 1)/initramfs.img"; \
    sdboot="usr/lib/systemd/boot/efi/systemd-bootx64.efi"; \
    sbsign \
        --key /run/secrets/secureboot_key \
        --cert /run/secrets/secureboot_cert \
        --output "/${sdboot}" \
        "/${sdboot}";'

FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=base-sd-signed,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build \
            --max-layers 256 \
            --prune /ostree \
            --prune /sysroot/ostree \
            > /run/src/out.ociarchive

FROM oci-archive:out.ociarchive as base-chunked
LABEL containers.bootc 1
ENV container=oci
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]

FROM signer as kernel
RUN --mount=type=bind,from=base-chunked,target=/target \
    --network=none \
    --mount=type=secret,id=secureboot_key \
    --mount=type=secret,id=secureboot_cert \
    --mount=type=tmpfs,dst=/tmp \
    --mount=type=tmpfs,dst=/var/tmp \
    <<EORUN
set -euxo pipefail
kver=$(basename $(find /target/usr/lib/modules -maxdepth 1 -mindepth 1 -type d -print0))
ukify_args="\
            --secureboot-private-key /run/secrets/secureboot_key \
            --secureboot-certificate /run/secrets/secureboot_cert \
            --measure \
            --output /boot/${kver}.efi"
bootc container ukify --rootfs /target --karg "\"$CMDLINE\"" -- ${ukify_args}
EORUN

FROM base-chunked
COPY --from=kernel /boot/*.efi /boot/EFI/Linux/